Molecule test
IKIM-Essen/EMCP-config pull request #59
Opened 2022-09-19 12:46 UTC by Infinity-ops

Added molecule to test ansible roles: miniconda, proxies, Poetry

2022-10-17 16:12 UTC, enasca requested changes
We need to execute tests on Ubuntu 22.04 as well, but other than that it looks ok. Any comments, @hfrSchmidt?

2022-10-20 08:47 UTC, enasca requested changes

2022-10-20 08:47 UTC, enasca commented on ansible/roles/poetry/tasks/poetry-install.yml
> +    content: "{{ cmd_poetry_bash_completions }}"
Shouldn't this be `cmd_poetry_bash_completions['stdout']`?

2022-10-20 09:07 UTC, enasca commented
By the way, those lint errors come from the new version of the linter catching more things. Fixing those now.

2022-10-20 10:37 UTC, enasca commented
Fixed the lint errors in #64. After it gets merged, we'll need to rebase this branch.

2022-10-21 13:50 UTC, enasca requested changes

2022-10-21 13:50 UTC, enasca commented on .github/workflows/molecule_workflow.yml
> +          python-version: '3.10'
Is it possible to change this back to `3.x`? I don't think we need 3.10 specifically.

2022-10-24 07:17 UTC, enasca approved these changes

2022-10-24 10:01 UTC, hfrSchmidt reviewed
I think it is not sufficient to just test with --version if the software is there in the verify step. This does not really ensure correct installation. 
But it is a start and I think for now it is good enough.

2022-10-24 10:01 UTC, hfrSchmidt commented on ansible/roles/proxies/molecule/default/verify.yml
> +  - debug: var=output.stdout_lines
If its not clear how to exactly do this, I suggest we defer the test of the proxies role to the next revision and remove it from the PR for now.

2022-10-24 10:46 UTC, enasca commented on ansible/roles/proxies/molecule/default/verify.yml
> +  - debug: var=output.stdout_lines
If we invoke the `shell` module in ansible, we should be able to do `echo $HTTPS_PROXY` and verify the output.

2022-10-24 11:34 UTC, hfrSchmidt commented on ansible/roles/proxies/molecule/default/verify.yml
> +  - debug: var=output.stdout_lines
Yes and then cross check with the values that are supposed to be there?

2022-11-02 08:26 UTC, enasca approved these changes
We're now sourcing the shell script in order to verify if it sets the variables correctly, which looks reasonable to me.

2022-11-02 08:32 UTC, hfrSchmidt approved these changes
Thanks for the contribution!

2022-11-02 09:02 UTC, merged